import "./globals.css";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import type { Metadata } from "next";
import { Poiret_One } from "next/font/google";
import Script from "next/script";
import { ThemeProvider } from "@mui/material";
// import poiretOne from "next/font/local";
import { theme } from "./theme";

const poiretOneFont = Poiret_One({
  subsets: ["latin", "cyrillic"],
  weight: "400",
});

// const poiretOneFont = poiretOne({ src: "../public/PoiretOne.ttf" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poiretOneFont.className}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>{children}</ThemeProvider>
        </AppRouterCacheProvider>
      </body>
      {/* <Script
        type="text/javascript"
        charset="UTF-8"
        src="//cdn.cookie-script.com/s/573dfe802bd14402d4b50415b57497c6.js"
      ></Script> */}
    </html>
  );
}
